### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by lizvladi-ds** [FlameInBrainSerj/mlops#1]
Так как ветка всего одна, не могу сделать PR и показать в коде
Скрин ошибки прилагаю
С такой ошибкой падает каждый шаг обучения модели
Подумай, почему же mlflow не может найти run (может где-то не там его ищет?:) ), поправь до дедлайна по проекту и тегни меня заново в этом ишью, когда можно будет забрать на проверку исправленный код
![image](https://github.com/user-attachments/assets/072b23fe-b35b-4836-a61f-37165a00ab23)

**Comment by FlameInBrainSerj** [comment]
@lizvladi-ds, привет, поправил) Не обратил внимание, что атрибут deprecated)
![image](https://github.com/user-attachments/assets/47de296f-dd7f-4f68-8f64-71ca87320f87)
![image](https://github.com/user-attachments/assets/8fd96d83-9455-48a6-b01f-64ae4fa6764f)

**Comment by FlameInBrainSerj** [comment]
Надеюсь, проблема была в этом)
